#
# Cmake Module to fix amqp-cpp
#

find_path(AMQPCPP_INCLUDE
  amqpcpp.h
  HINTS
  ${DEPS_DIR}/amqpcpp/include
  $ENV{HOME}/usr/local/include
  )

find_library(AMQPCPP_LIBRARIES
  amqp-cpp
  HINTS
  ${DEPS_DIR}/amqpcpp/lib
  $ENV{HOME}/usr/local/lib
  )

message(-- "amqp-cpp:")
if(AMQPCPP_INCLUDE-NOTFOUND)
  message("---- AMQPCPP_INCLUDE: NOT FOUND")
else(AMQPCPP_INCLUDE-NOTFOUND)
  message("---- AMQPCPP_INCLUDE: ${AMQPCPP_INCLUDE}")
endif(AMQPCPP_INCLUDE-NOTFOUND)


message(-- "amqp-cpp:")
if(AMQPCPP_LIBRARIES-NOTFOUND)
  message("---- AMQPCPP_LIBRARIES: NOT FOUND")
else(AMQPCPP_LIBRARIES-NOTFOUND)
  message("---- AMQPCPP_LIBRARIES: ${AMQPCPP_LIBRARIES}")
endif(AMQPCPP_LIBRARIES-NOTFOUND)


if (AMQPCPP_INCLUDE-NOTFOUND OR LIBAMQPCPP-NOTFOUND)
  set(AMQPCPP_FOUND no)
else (AMQPCPP_INCLUDE-NOTFOUND OR LIBAMQPCPP-NOTFOUND)
  set(AMQPCPP_FOUND yes)
  set(AMQPCPP_INCLUDE_DIRS ${AMQPCPP_INCLUDE})
endif(AMQPCPP_INCLUDE-NOTFOUND OR LIBAMQPCPP-NOTFOUND)
